### ISSUE TITLE
Support Multi Texture Model

### ISSUE THREAD

**Issue by yuzuka4573** [DenchiSoft/Live2DLighting#1]
Thank you for make great solution for lighting Live2D

#Issue
In CubismTextureReplacer.cs, It can only replace one texture

#Suggest 
- Add List or Array variable
- put texture data to variable in order
- change script in Reload() like this
```
// after "if(newTexture != null)" , "newTexture" is Array or List
 foreach (var drawable in model.Drawables.ToList())
                {
                    CubismRenderer r = drawable.gameObject.GetComponent<CubismRenderer>();

                    if (r != null)
                    {
                        r.MainTexture = newTexture[drawable.TextureIndex];
                    }
                }
```
(Actually, it is my first suggest in GitHub...If you didn't understand, I say sorry)

**Comment by DenchiSoft** [comment]
Thank you for the suggestion!

I implemented multi-texture support including partial texture replacement in 9c3c1b3. Let me know if this works for you. I don't have a model with multiple textures to test this right now.

**Comment by yuzuka4573** [comment]
Thank you for fix that code!  
It works in my environment.  
[![Image from Gyazo](https://i.gyazo.com/dcd0a1dfe3d9ee2352af3debda89afd3.gif)](https://gyazo.com/dcd0a1dfe3d9ee2352af3debda89afd3)
(By the way, I want short instruction to make lighting with own model... )
Thank you !!

**Comment by DenchiSoft** [comment]
Thank you for testing. 

I might add a small tutorial in the future. But there isn't really much more to know about it. The lighting setup works as seen in the Unity scene and the normal map has to be painted by hand. This channel has some examples on how to do that: https://www.youtube.com/channel/UCwh_jH8ExX052-uQb32xDMg

You can use any graphics software like Photoshop or Sai.
